### ISSUE TITLE
is 11.2.5 = to 11.2.6?

### ISSUE THREAD

**Issue by iambenmitchell** [MTJailed/UnjailMe#10]
If you can brute force the random ID and get the exploit working on 11.2.5 would it also work on 11.2.6? or did they patch it?

**Comment by MTJailed** [comment]
They patched it, you can still intercept session ID's, they did not patch that part, but they replaced the session ID with arc4random instead of the client port.
It should be possible I read on reddit by some people to bruteforce the port as arc4random gives us 2^32 possibilities.

However, fear not Abraham Masri's securityd-racer2 PoC can be turned into an exploit for iOS11.3 and under that also will give root permissions and escapes the sandbox ;)
